# Generated by Django 3.2.9 on 2021-11-12 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['title'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
